#ifndef OSGEARTHX_COM_SOURCE_CLASS_TYPE_IDL_H
#define OSGEARTHX_COM_SOURCE_CLASS_TYPE_IDL_H 1

[
	uuid(f5af84f7-5b55-4256-ae40-7372bae9cd75)
]
typedef enum SourceClassType
{
	TILE_SOURCE_AGGLITE = 0,
	TILE_SOURCE_ARCGIS,
	TILE_SOURCE_BING,
	TILE_SOURCE_COLOR_RAMP,
	TILE_SOURCE_DEBUG,
	TILE_SOURCE_GDAL,
	TILE_SOURCE_MBTILES,
	TILE_SOURCE_NOISE,
	TILE_SOURCE_OSG,
	TILE_SOURCE_TILE_CACHE,
	TILE_SOURCE_TILE_SERVICE,
	TILE_SOURCE_TMS,
	TILE_SOURCE_VPB,
	TILE_SOURCE_WCS,
	TILE_SOURCE_WMS,
	TILE_SOURCE_XYZ,
	TILE_SOURCE_YAHOO,

	VECTOR_SOURCE_GEOM,
	VECTOR_SOURCE_SIMPLE,
	VECTOR_SOURCE_STENCIL,

	FEATURE_SOURCE_OGR,
	FEATURE_SOURCE_TFS,
	FEATURE_SOURCE_WFS

}SourceClassType;

#endif