/*
	@brief COM EarthObject对象类类型枚举
	@author Hao Luo
	@date 2014/11/27
*/

#ifndef OSGEARTHX_COM_EARTH_OBJECT_CLASS_TYPE_H
#define OSGEARTHX_COM_EARTH_OBJECT_CLASS_TYPE_H 1

[
	uuid(69297707-bc99-43c6-8e4a-68f10dd4de68),
	helpstring("接口ID枚举")
]
typedef enum EarthObjectClassType
{
	// 1 : EarthObject
	EARTH_GROUP = 2,

	IMAGE_SURFACE_LAYER,
	VECTOR_SURFACE_LAYER,
	ELEVATION_SURFACE_LAYER,
	TERMASK_SURFACE_LAYER,

	EXTERNAL_GRATICULE,
	EXTERNAL_SKY,
	EXTERNAL_VIEWPOINT,

	ANNOTATION_TEXT_LABEL,
	ANNOTATION_MODEL,
	ANNOTATION_IMAGE_OVERLAY,
	ANNOTATION_FEATURE,
	ANNOTATION_PLACE,
	ANNOTATION_CIRCLE,
	ANNOTATION_RECTANGLE,
	ANNOTATION_ELLIPSE,

	LABEL_SET_LAYER,
	MODEL_SET_LAYER,
	OVERLAY_IMAGE_SET_LAYER,
	SHAPE_SET_LAYER,
	PLACE_SET_LAYER,
	VIEWPOINT_SET_LAYER
}EarthObjectClassType;

#endif